### ISSUE TITLE
Running github runner via sudo - missing environment

### ISSUE THREAD

**Issue by SystemKeeper** [cloudbase/garm#113]
As noted in https://github.com/cloudbase/garm/issues/90#issuecomment-1575685747 we try to use an image that is as close as possible to the github action one. We noticed that some workflows fail on the selfhosted runners (but succeed on GitHub), since the executables could not be found. After investigating I noticed that the runner user only has the following in it's PATH environment:
```
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
```

in contrast when manually logging in as `runner` I have this:

```
/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

which is added to `/etc/environment`. 

This happens because the the configuration of the github runner is done with `sudo` and sudo by default replaced the PATH environment as specified in `/etc/sudoers`:

```
# cat /etc/sudoers | grep secure
Defaults	secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
```

(the `config.sh` file calls `env.sh` which then saves the PATH inside of the file `.path`)

So question now would be if this is intended or if this behavior should be changed? I see two possibilities here:
1. We change the execution of the `config.sh` file to not use `sudo` and use `su -c '...' runner` instead (would be a change on garm)
2. We keep the current behavior (if it's intended) and change `/etc/sudoers` on our image.

(of course there are more ways as well, lika adjusting the workflows, changing the template, etc., but these were the most obvious ones to me)

Some example outputs:
```
# su --command 'echo $PATH'
/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

sudo -u runner -E cat /proc/self/environ
... PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin...

# sudo -u runner -E bash -c 'echo $PATH'
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
```

**Comment by gabriel-samfira** [comment]
Heya @SystemKeeper !

The #115 PR should fix this. Essentially we switched to running the install script using the runner user via `su`. Have a look and let me know if it works for you.

Also, note that there have been some changes in recent commits that reverts some of the `Wait()` calls we added to fix the leftover runners you were seeing, but I've added some locks that should prevent that scenarios from happening. Take the #115 branch for a spin and let me know if you experience the previous issues with it.
