### ISSUE TITLE
Support SIGHUP for logrotate

### ISSUE THREAD

**Issue by SystemKeeper** [cloudbase/garm#114]
When rotating `garm.log` the file handlers need to be re-opened. Currently we just do a restart of garm when we rotated the log. Would be nice if we could just send a `SIGHUP` (or something else) to gracefully to this without the need to restart.

**Comment by gabriel-samfira** [comment]
Hmm. If you specified the log path specifically and are not logging to syslog, garm should rotate automatically when it reaches ~500 MB or 20 days. See: https://github.com/cloudbase/garm/blob/main/util/util.go#L170-L176

We can also add a `SIGHUP` handler of course.

**Comment by SystemKeeper** [comment]
Oh I see. I wasn't aware of that build-in functionality... Hm, I think SIGHUP wouldn't hurt for people wanting to use logrotate, but I guess the build-in functionality should be be more visible in the future?!
