### ISSUE TITLE
Image customization through pre-runner script

### ISSUE THREAD

**Issue by pothos** [cloudbase/garm#130]
Sometimes the image has temporary problems that prevent the runner installation or the workflow has an assumption that isn't true for the used image but the workflow can't be changed. Like for other customizations one could build a custom image to address this. However, building custom images is a hurdle and for a temporary one-line fix it might be nicer to address it by passing one or more pre-runner-install scripts in `--extra-specs`.

To keep it generic the content could be inline text or binary data, and for Windows the filename or at least extension would need to be given for correct execution. Whether this becomes part of the instance's regular garm userdata or gets executed after it is implementation-defined.

The feature should be documented with the mention that the preferred approach would be to customize the image or if possible run the customization from the workflow.

**Comment by gabriel-samfira** [comment]
This PR splits the cloudconfig (among other) package from garm. As part of the move, I've also added the ability to completely override the runner install script, as well as add [pre-install scripts](https://github.com/cloudbase/garm-provider-common/blob/main/cloudconfig/util.go#L21-L34) via `extra_specs`.

This will be part of the next release.
