### ISSUE TITLE
garm-cli builds for Windows

### ISSUE THREAD

**Issue by krische** [cloudbase/garm#155]
I understand if you don't want the "server" part built for Windows, but can you build and publish Windows builds of the cli?

**Comment by gabriel-samfira** [comment]
Sure thing! Will be happy to! I think the server may run on Windows as well. Will have to test it out. In any case, I will publish the client for the latest release (and all future releases), tomorrow.

**Comment by gabriel-samfira** [comment]
Surprisingly, the server seems to work well on Windows. However, it has no Windows service manager support, so something like [nssm](https://nssm.cc/) will need to be used if anyone wants to run it as a service on Windows. I will add the necessary handlers to enable native Windows service support in directly in the binary. But that will be done later.

**Comment by gabriel-samfira** [comment]
Windows binaries have been added to the latest release: https://github.com/cloudbase/garm/releases/tag/v0.1.3

Give them a shot and let me know if you encounter any issues.
