### ISSUE TITLE
github.com/lxc/lxd moved to github.com/lxc/incus

### ISSUE THREAD

**Issue by mergar** [cloudbase/garm#177]
Look's like https://github.com/lxc/lxd is deprecated

**Comment by gabriel-samfira** [comment]
Indeed. Need to update dependencies. For the moment, we may use `https://github.com/canonical/lxd` until things settle down and we know how much `LXD` and `incus` are compatible.

**Comment by gabriel-samfira** [comment]
So, given the fact that LXD has been relicensed to AGPLv3, we won't be updating this dependency.

We will however convert the built-in lxd provider to an external provider and remove the internal one. GARM needs to stay Apache 2.0.

There will most likely be a separate incus provider, as I expect they will diverge soon.

**Comment by gabriel-samfira** [comment]
The internal LXD provider has been removed by:

  * https://github.com/cloudbase/garm/pull/194.

Two new external providers have been created from that code. One for LXD and one for Incus:

* https://github.com/cloudbase/garm-provider-lxd
* https://github.com/cloudbase/garm-provider-incus
