### ISSUE TITLE
Wrong tag/version used when building master

### ISSUE THREAD

**Issue by SystemKeeper** [cloudbase/garm#186]
Might be an issue with our repo clone, not sure, but currently this happens:

```
root@65 /opt/garm-src # make
Building garm v0.1.0-269-g05e1796
Binaries are available in /opt/garm-src/bin

root@65 /opt/garm-src # git log -1
commit 05e179604dedeada5354495ab319633fb444a0ab (HEAD -> main, origin/main, origin/HEAD)
Merge: 7f4f4bd b9c7c93
Author: Gabriel <gsamfira@cloudbasesolutions.com>
Date:   Tue Nov 21 20:56:24 2023 +0200

    Merge pull request #183 from gabriel-samfira/force-remove-runner
    
    Add force delete runner
```

So the version is still tagged as 0.1.0, although the repo is at master. It works when a tag is directly checked out.

**Comment by gabriel-samfira** [comment]
eecchh. Will look into it. I need to work on my Makefile-fu.

**Comment by gabriel-samfira** [comment]
ahh wait. That is to be expected. Sadly, github creates lightweight tags when creating a new release. To generate the version nr we do a:

```bash
VERSION ?= $(shell git describe --tags --match='v[0-9]*' --dirty --always)
```

Which will only return the first lightweight tag it seems, not the latest. For the next release (and every release after that), I will manually generate an annotated tag and push it, which should better reflect the actual version nr.

For now, the best hint of the actual version you're running is the trailing commit nr: `g05e1796`. If you strio away the leading `g`, you have the short commit nr of what you're running: `05e1796`. You can view info on that commit by running `git log 05e1796`.

**Comment by gabriel-samfira** [comment]
A new annotated tag has been created `v0.1.4-rc1`. From now on, we'll only create annotated tags, so make will properly reflect the latest version plus the commit hash.
