### ISSUE TITLE
Support for running workflows bare-metal?

### ISSUE THREAD

**Issue by awalvie** [cloudbase/garm#230]
Love the project, kudos to the team! I wanted to check if there's support for running workflows bare-metal?

By a bare-metal, I mean something that can just run the workflows as systemd services on hosts (Ref: [Configuring the self-hosted runner application as a service](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/configuring-the-self-hosted-runner-application-as-a-service)) instead of inside virtual machines. I tried looking through the documentation for something similar but didn't find anything similar.

**Comment by gabriel-samfira** [comment]
I will close this issue for now. Feel free to reopen if the Equinix or Ironic providers are not suitable, or if you have another provider in mind.
