### ISSUE TITLE
Tag validation should be case insensitive

### ISSUE THREAD

**Issue by Hdom** [cloudbase/garm#295]
Hello, I've noticed that GitHub's runner software [tag validation is case insensitive](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/using-labels-with-self-hosted-runners#creating-a-custom-label) but the login in findPoolByTags seems to be case sensitive. 

https://github.com/cloudbase/garm/blob/main/database/sql/pools.go#L187

Our current workaround includes lowercasing input tags and lowercasing stored tags in the comparison:
```
for i, tag := range tags {
    tags[i] = strings.ToLower(tag)
}
where := fmt.Sprintf("lower(tags.name) in ? and %s = ? and enabled = true", fieldName)
```

Do you think we could get this included?

**Comment by gabriel-samfira** [comment]
We can add a `COLLATE NOCASE` in that `WHERE tags.name IN` clause. Adding a PR soon.

**Comment by gabriel-samfira** [comment]
can you give this a try: https://github.com/cloudbase/garm/pull/296
