### ISSUE TITLE
Correct way to delete a pool with runners

### ISSUE THREAD

**Issue by olevole** [cloudbase/garm#3]
`garm-cli` does not allow you to delete a pool if runners are already running:
```
garm-cli pool delete e2f1f563-4b51-48cf-94e4-87dc00a0d42f
Error: sending request: error in API call: pool has runners
```
However, trying to reduce the number of runners to zero does not destroy the runner:
```
garm-cli pool update e2f1f563-4b51-48cf-94e4-87dc00a0d42f --min-idle-runners 0
// another test: 
garm-cli pool update e2f1f563-4b51-48cf-94e4-87dc00a0d42f --enabled=false
```
Also there is no `garm-cli runner delete|rm|destroy` to destroy idle runner. 

Deleting a record directly in the SQL table helps, but it would be nice to delete (+ calling the `DeleteInstance` function) via the CLI. Thank you!

**Comment by gabriel-samfira** [comment]
Hi Oleg!

The ability to remove a runner is in the works. Right now, a really hacky way to do it is to disable the pool using:

```bash
garm-cli pool update POOL_ID --enabled=false
```

Then remove the runners within the provider (ie: lxc delete -f VM_NAME). Allow enough time for github to pick up that the runners are offline and restart garm. It will consolidate on startup and remove any orphaned runners from github.

Alternatively, after disabling the pool, you can simply use the runners with a dummy workflow. Garm will take care of the cleanup when github sends a webhook notification that the runner has finished it's task.

Garm will not automatically downscale runners when changing ```min-idle-runners``` as that may inadvertently cancel a potential running job. It will also not allow deletion of a pool with runners for the same reason. While it is bad UX to not have a ```delete``` option, destructive operations should be implemented carefully, or risk canceling jobs that may have been running for hours.

The option to remove individual runners as well as removing a pool with runners in it will be added soon. It will be an explicit and forceful action with mandatory flags that warn the user that jobs (potentially very long running ones), may be canceled by that action.

Will ping back here when the functionality has been added.

**Comment by olevole** [comment]
Thanks, you created a great project!

**Comment by gabriel-samfira** [comment]
Manual runner removal was added to the main branch, as well as a bootstrap timeout threshold for new runners. Test it out, let me know if it works for you.

To remove a runner:

```bash
garm-cli runner rm --force-remove-runner [runner-name]
```

To change the default runner bootstrap timeout (expressed in minutes):

```bash
garm-cli pool update [pool-id] --runner-bootstrap-timeout=10
```

Any runner that has not joined github after the configured amount of time, will be removed and replaced. Will update the documentation soon.

**Comment by olevole** [comment]
Awesome, works like a charm:
```
garm-cli runner delete --force-remove-runner=true garm-61a90723-8a1c-41bc-95b5-8b5a6a977037
```

and the **DeleteInstance** hook was called/triggered correctly. Thanks again for your promptness!
