### ISSUE TITLE
Conflict on garm-cli commands that already have -f defined

### ISSUE THREAD

**Issue by Hdom** [cloudbase/garm#305]
https://github.com/cloudbase/garm/blob/54aa3815dfaa03775188077d34b9d3ec3f5b103d/cmd/garm-cli/cmd/root.go#L57

This persistent flag added to all commands for the new json format feature is breaking commands that already had an "f" option, like `init`. Most likely will also affect `runner delete` due to `force-remove-runner`.

Error: 
```shell
panic: unable to redefine 'f' shorthand in "init" flagset: it's already used for "full-name" flag
```

**Comment by gabriel-samfira** [comment]
:melting_face: 

Will fix in the morning. I have a new found respect for the curl project and their many command line options that do not overlap.
