### ISSUE TITLE
Missing --no-default--labels on windows cloudconfig template in common

### ISSUE THREAD

**Issue by Hdom** [cloudbase/garm#308]
Hello, seems that when the no-default-labels feature was introduced it was only included in the linux template:
https://github.com/cloudbase/garm-provider-common/commit/b658eb8b8358402e811fb4327bbeafe0e011f7db

Should this be included in the windows template?

**Comment by gabriel-samfira** [comment]
Yes, it should. We should add integration tests for windows as well, and make sure we test for this as well. Will add the flag in the windows userdata asap.
