### ISSUE TITLE
Possibility to scale down to zero

### ISSUE THREAD

**Issue by kim0** [cloudbase/garm#32]
I would like to support a large number of repos on a fairly small box. For that it would be great to be able to scale the runners down to zero. Such that the first runner is only started after the first webhook has hit. 

If that is possible today in any way, please let me know how. Thanks

**Comment by gabriel-samfira** [comment]
It should be. Simply create a pool or update a pool with ```--min-idle-runners=0```. Garm will create a runner when a workflow is started. Let me know if it works for you.

**Comment by gabriel-samfira** [comment]
Note, garm will not scale down existing idle runners. If you already have a pool created, after setting ```min-idle-runners``` to 0, you will have to manually remove the existing idle runners for that pool using:

```garm-cli runner rm -f <runner name>```
