### ISSUE TITLE
garm removes externally managed runners

### ISSUE THREAD

**Issue by MoritzKeppler** [cloudbase/garm#40]
first of all: thanks for providing this cool runner orchestrator!

One observation: garm cleans up orphaned runners. "non-garm-managed"-runners, for example manually added runners, that are accidentally in state `offline` will get removed too.
How about if garm only takes care of the runners who either follow the own naming scheme (garm-*) or have certain labels?

https://github.com/cloudbase/garm/blob/996102fd980aeab73fef0f02332f60698afa3be7/runner/pool/pool.go#L144
<sub> Moritz Keppler <moritz.keppler@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)</sub>

**Comment by gabriel-samfira** [comment]
Hi @MoritzKeppler ,

That is a great point! We add the controller ID as a tag on all runners spawned by ```garm```. We should filter out any runner that was not created by us.

Thanks for bringing this up! I will create a PR in the following days to fix this behavior. Most likely near the end of the week. Apologies if this caused you issues.

**Comment by MoritzKeppler** [comment]
Thanks a lot! And let me know if we can support. Glad to contribute!

**Comment by gabriel-samfira** [comment]
Found some time to look at this.

Could you test out the code [in this PR](https://github.com/cloudbase/garm/pull/41) and see if it fixes things for you?

**Comment by MoritzKeppler** [comment]
lgtm, thanks!
