### ISSUE TITLE
ListInstances of of openstack provider example returns invalid json array 

### ISSUE THREAD

**Issue by MoritzKeppler** [cloudbase/garm#74]
ListInstances in https://github.com/cloudbase/garm/blob/main/contrib/providers.d/openstack/garm-external-provider returns a sequence of json objects but not a json array. Guess we need to encapsulate the whole jq string in '[...]', right?
```
echo ${INSTANCES} | jq -r '[
        .[] | .Properties * {
            provider_id: .ID,
            name: .Name,
            status: {"ACTIVE": "running", "SHUTOFF": "stopped", "BUILD": "pending_create", "ERROR": "error", "DELETING": "pending_delete"}[.Status]
        }]'
```

**Comment by gabriel-samfira** [comment]
Indeed. It is a typo on my part. Will push a fix soon.

**Comment by gabriel-samfira** [comment]
Also, make sure you use a recent version of the openstack clients (I installed from pip). Older versions seem to return properties as a string instead of a dict.
