### ISSUE TITLE
nit: callback_url vs metadata_url

### ISSUE THREAD

**Issue by maigl** [cloudbase/garm#88]
I think we might have a small inconsistency in how to configure callback_url vs metadata_url:
Both URLs getting passed to the provider, both URLs have some suffix: `/status` and `/runner-registration-token` when actually called.

```
https://garmserver/api/v1/callbacks/status
https://garmserver/api/v1/metadata/runner-registration-token
```

`/runner-registration-token` is appended in the (openstack) provider (both, the bash version and the go version)
but the `/status` is appended nowhere, this has to be added directly in the configuration by the user.

I think a symmetric configuration would be much nicer, like this:
```
[default]
callback_url = "https://garmserver/api/v1/callbacks"
metadata_url = "https://garmserver/api/v1/metadata"
```

Shall I change that .. or do you prefer the way it is ?

<sub>Michael Kuhnt <michael.kuhnt@mercedes-benz.com> Mercedes-Benz Tech Innovation GmbH ([ProviderInformation](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md))
</sub>

**Comment by gabriel-samfira** [comment]
I completely forgot about this one. Yes, we can consolidate the behavior. Feel free to open a PR.
