### ISSUE TITLE
larger disk size?

### ISSUE THREAD

**Issue by hallyn** [cloudbase/garm#89]
Hi, I'm using garm with vms (through lxd provider).  Tests are running out of disk space.  Is there a way to edit the pool to specify a disk size?

**Comment by gabriel-samfira** [comment]
Hi @hallyn !

All VM characteristics should be set by creating a profile in lxd and modifying it. That profile can then be set as a ```flavor``` in garm.

I usually go with:

```
lxc profile copy default medium
```

Then I edit the new profile and set CPU, memory and disk:

```
lxc profile edit medium
```

Then we can set the ```medium``` profile as a ```flavor``` in a pool. 

```
garm-cli pool update --flavor medium <pool_id>
```
