### ISSUE TITLE
Set DisableUpdatesOnBoot with LXD?

### ISSUE THREAD

**Issue by SystemKeeper** [cloudbase/garm#93]
Maybe I am not seeing it, but is there a way to use `DisableUpdatesOnBoot` (implemented with https://github.com/cloudbase/garm/pull/87) also with LXD? I can change the default in the source, but I am not seeing how I could set the parameter for a specific pool?!

**Comment by gabriel-samfira** [comment]
This is a per-provider setting which is not yet added in LXD. Currently only the external OpenStack provider has it. I can add it to LXD shortly.

**Comment by SystemKeeper** [comment]
>  I can add it to LXD shortly.

That would be great, thank you!

**Comment by gabriel-samfira** [comment]
Grab the latest commit and update your pool as described in the PR. Updates should be skipped for all runners spawned in that pool. Let me know if it works out!
