### ISSUE TITLE
Runner not correctly deleted

### ISSUE THREAD

**Issue by SystemKeeper** [cloudbase/garm#96]
So this looks a bit different than #91 (at least to me).

This is the garm log of the runner `garm-g1bTYEDUUDJ5`

```
# cat /var/log/garm/garm.log | grep garm-g1bTYEDUUDJ5
2023/06/05 10:56:57 creating instance garm-g1bTYEDUUDJ5 in pool f52a63ee-7af9-4a19-b7f0-4f1f67de1579
2023/06/05 11:22:03 marking instance garm-g1bTYEDUUDJ5 as pending_delete
2023/06/05 11:26:22 Runner instance for garm-g1bTYEDUUDJ5 is no longer on the provider, removing from github
2023/06/05 11:26:23 Removing garm-g1bTYEDUUDJ5 from database
```

But still I see this one on LXD:

```
# lxc list | grep garm-g1bTYEDUUDJ5
| garm-g1bTYEDUUDJ5 | RUNNING | 172.17.0.1 (docker0) | fd42:25c4:b166:134a:216:3eff:fe14:b8c8 (eth0) | CONTAINER | 0         |
```

Config shows the correct pool:

```
# lxc config show garm-g1bTYEDUUDJ5
architecture: x86_64
config:
  image.architecture: x86_64
  image.description: Ubuntu 22.04 LTS server (20230518)
  image.os: ubuntu
  image.release: jammy
  user.os-arch: amd64
  user.os-type: linux
  user.runner-controller-id: fb7342c7-c9a9-4c35-898d-c781d99443b6
  user.runner-pool-id: f52a63ee-7af9-4a19-b7f0-4f1f67de1579
  ...
```

Inside the container the runner was run correctly as far as I can see. Only thing I noticed is a fail on eth0:

<details>

```
Jun  5 10:59:46 garm-g1bTYEDUUDJ5 runsvc.sh[3778]: √ Connected to GitHub
Jun  5 10:59:47 garm-g1bTYEDUUDJ5 runsvc.sh[3778]: Current runner version: '2.304.0'
Jun  5 10:59:47 garm-g1bTYEDUUDJ5 runsvc.sh[3778]: 2023-06-05 10:59:47Z: Listening for Jobs
Jun  5 10:59:51 garm-g1bTYEDUUDJ5 runsvc.sh[3778]: 2023-06-05 10:59:51Z: Running job: qa
Jun  5 10:59:58 garm-g1bTYEDUUDJ5 systemd[1]: systemd-timedated.service: Deactivated successfully.
Jun  5 11:02:41 garm-g1bTYEDUUDJ5 systemd[1]: Starting Download data for packages that failed at package install time...
Jun  5 11:02:42 garm-g1bTYEDUUDJ5 systemd[1]: update-notifier-download.service: Deactivated successfully.
Jun  5 11:02:42 garm-g1bTYEDUUDJ5 systemd[1]: Finished Download data for packages that failed at package install time.
Jun  5 11:05:01 garm-g1bTYEDUUDJ5 CRON[4213]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Jun  5 11:09:01 garm-g1bTYEDUUDJ5 CRON[4277]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)
Jun  5 11:09:06 garm-g1bTYEDUUDJ5 systemd[1]: Starting Clean php session files...
Jun  5 11:09:07 garm-g1bTYEDUUDJ5 systemd[1]: phpsessionclean.service: Deactivated successfully.
Jun  5 11:09:07 garm-g1bTYEDUUDJ5 systemd[1]: Finished Clean php session files.
Jun  5 11:11:39 garm-g1bTYEDUUDJ5 systemd-networkd[194]: eth0: Could not set route: Connection timed out
Jun  5 11:11:39 garm-g1bTYEDUUDJ5 systemd-networkd[194]: eth0: Failed
Jun  5 11:14:15 garm-g1bTYEDUUDJ5 systemd[1]: snapd.service: Watchdog timeout (limit 5min)!
Jun  5 11:14:15 garm-g1bTYEDUUDJ5 systemd[1]: snapd.service: Killing process 2801 (snapd) with signal SIGABRT.
Jun  5 11:14:15 garm-g1bTYEDUUDJ5 systemd[1]: Starting Cleanup of Temporary Directories...
Jun  5 11:14:15 garm-g1bTYEDUUDJ5 systemd[1]: snapd.service: State 'stop-watchdog' timed out. Killing.
Jun  5 11:14:15 garm-g1bTYEDUUDJ5 systemd[1]: snapd.service: Killing process 2801 (snapd) with signal SIGKILL.
Jun  5 11:14:15 garm-g1bTYEDUUDJ5 systemd[1]: snapd.service: Main process exited, code=killed, status=9/KILL
Jun  5 11:14:15 garm-g1bTYEDUUDJ5 systemd[1]: snapd.service: Failed with result 'watchdog'.
Jun  5 11:14:15 garm-g1bTYEDUUDJ5 systemd[1]: snapd.service: Consumed 1.816s CPU time.
Jun  5 11:14:15 garm-g1bTYEDUUDJ5 systemd[1]: snapd.service: Scheduled restart job, restart counter is at 1.
Jun  5 11:14:15 garm-g1bTYEDUUDJ5 systemd[1]: Stopped Snap Daemon.
Jun  5 11:14:15 garm-g1bTYEDUUDJ5 systemd[1]: snapd.service: Consumed 1.816s CPU time.
Jun  5 11:14:15 garm-g1bTYEDUUDJ5 systemd[1]: Starting Snap Daemon...
Jun  5 11:14:26 garm-g1bTYEDUUDJ5 systemd[1]: systemd-tmpfiles-clean.service: Deactivated successfully.
Jun  5 11:14:26 garm-g1bTYEDUUDJ5 systemd[1]: Finished Cleanup of Temporary Directories.
Jun  5 11:14:26 garm-g1bTYEDUUDJ5 systemd[1]: systemd-tmpfiles-clean.service: Consumed 6.776s CPU time.
Jun  5 11:16:08 garm-g1bTYEDUUDJ5 systemd[1]: snapd.service: start operation timed out. Terminating.
Jun  5 11:16:10 garm-g1bTYEDUUDJ5 systemd[1]: snapd.service: Failed with result 'timeout'.
Jun  5 11:16:10 garm-g1bTYEDUUDJ5 systemd[1]: snapd.service: Unit process 4403 (systemd-detect-) remains running after unit stopped.
Jun  5 11:16:10 garm-g1bTYEDUUDJ5 systemd[1]: Failed to start Snap Daemon.
Jun  5 11:16:11 garm-g1bTYEDUUDJ5 systemd[1]: snapd.service: Consumed 16.535s CPU time.
Jun  5 11:16:12 garm-g1bTYEDUUDJ5 systemd[1]: snapd.service: Scheduled restart job, restart counter is at 2.
Jun  5 11:16:13 garm-g1bTYEDUUDJ5 CRON[4409]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Jun  5 11:16:13 garm-g1bTYEDUUDJ5 systemd[1]: Stopped Snap Daemon.
Jun  5 11:16:13 garm-g1bTYEDUUDJ5 systemd[1]: snapd.service: Consumed 16.616s CPU time.
Jun  5 11:16:13 garm-g1bTYEDUUDJ5 systemd[1]: snapd.service: Found left-over process 4403 (systemd-detect-) in control group while starting unit. Ignoring.
Jun  5 11:16:13 garm-g1bTYEDUUDJ5 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jun  5 11:16:13 garm-g1bTYEDUUDJ5 systemd[1]: Starting Snap Daemon...
Jun  5 11:18:02 garm-g1bTYEDUUDJ5 systemd[1]: snapd.service: start operation timed out. Terminating.
Jun  5 11:18:05 garm-g1bTYEDUUDJ5 systemd[1]: snapd.service: Failed with result 'timeout'.
Jun  5 11:18:06 garm-g1bTYEDUUDJ5 systemd[1]: snapd.service: Unit process 4403 (systemd-detect-) remains running after unit stopped.
Jun  5 11:18:06 garm-g1bTYEDUUDJ5 systemd[1]: Failed to start Snap Daemon.
Jun  5 11:19:59 garm-g1bTYEDUUDJ5 systemd[1]: snapd.service: Consumed 16.746s CPU time.
Jun  5 11:23:12 garm-g1bTYEDUUDJ5 systemd[1]: snapd.service: Scheduled restart job, restart counter is at 3.
Jun  5 11:25:24 garm-g1bTYEDUUDJ5 systemd[1]: Stopped Snap Daemon.
Jun  5 13:31:30 garm-g1bTYEDUUDJ5 dockerd[400]: time="2023-06-05T13:02:51.192387663Z" level=error msg="Failed to get event" error="rpc error: code = Unavailable desc = transport is closing" module=libcontainerd namespace=moby
Jun  5 13:31:30 garm-g1bTYEDUUDJ5 dockerd[400]: time="2023-06-05T13:07:19.863280275Z" level=warning msg="grpc: addrConn.createTransport failed to connect to {unix:///var/run/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial unix:///var/run/containerd/containerd.sock: timeout\". Reconnecting..." module=grpc
Jun  5 13:31:30 garm-g1bTYEDUUDJ5 dockerd[400]: time="2023-06-05T13:08:48.582458995Z" level=warning msg="grpc: addrConn.createTransport failed to connect to {unix:///var/run/containerd/containerd.sock  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial unix:///var/run/containerd/containerd.sock: timeout\". Reconnecting..." module=grpc
Jun  5 13:31:30 garm-g1bTYEDUUDJ5 dockerd[400]: time="2023-06-05T13:08:55.071362909Z" level=error msg="Failed to get event" error="rpc error: code = Unavailable desc = transport is closing" module=libcontainerd namespace=plugins.moby
```

</details>

Any idea about that?

**Comment by gabriel-samfira** [comment]
Would you mind providing the garm log from the moment that runner was created up until where it was removed?

I see that it was marked for deletion. Normally, after about 5 seconds that runner should have veen removed. But I see that after almost 5 minutes, the cleanup routine runs and finds it, which is strange.

The log may help.

**Comment by skjnldsv** [comment]
@gabriel-samfira btw, thanks for being so active and helping! We're running an average of 11 runners continuously during working hours. 1289 self hosted runners yesterday only! We do have a lot of data and use cases, so feel free to ask if we can help with anything else! :hugs: :bow: 
We're loving garm so far!!

**Comment by SystemKeeper** [comment]
> Would you mind providing the garm log from the moment that runner was created up until where it was removed?

Mail send to you, thanks! 

> I see that it was marked for deletion. Normally, after about 5 seconds that runner should have veen removed. But I see that after almost 5 minutes, the cleanup routine runs and finds it, which is strange.

Well, the cleanup routine does _not_ find it, right? It removes it from github, because it can't find it locally?

**Comment by gabriel-samfira** [comment]
> Well, the cleanup routine does _not_ find it, right? It removes it from github, because it can't find it locally?

This bit:

> 2023/06/05 11:22:03 marking instance garm-g1bTYEDUUDJ5 as pending_delete

happens when github sends a hook telling garm that the job that ```garm-g1bTYEDUUDJ5``` was handling was ```completed``` and the runner should be removed. At that point, garm marks the runner for deletion, which happens during the ```consolidate()``` loop. That loop runs every 5 seconds and is responsible for spinning up runners found in ```pending_create```, removing runners found in ```pending_delete```.

Will investigate and see where this croaks.

**Comment by SystemKeeper** [comment]
I see. I was just expecting now to see the other way round, like "Found on provider, but not on github" when the container is still there.

**Comment by gabriel-samfira** [comment]
First some context:

This line:

> 2023/06/05 11:22:03 marking instance garm-g1bTYEDUUDJ5 as pending_delete

happens when a job is ```completed``` (or canceled) and garm is instructed to remove the runner. After the instance is put in ```pending_delete```, the ```consolidate()``` function runs ```deletePendingInstances()``` which runs ```provider.DeleteInstance()``` (this removes the instance from LXD)

This action should have run, or at least started running at ```2023/06/05 11:22:03```. 

Thse 2 lines:

> 2023/06/05 11:26:22 Runner instance for garm-g1bTYEDUUDJ5 is no longer on the provider, removing from github
> 2023/06/05 11:26:23 Removing garm-g1bTYEDUUDJ5 from database

happen in the function that checks every 5 minutes for orphaned github runners. What happens here, is that we look for runners on github that are in ```offline``` state. We cross check those runners with the ones we see in out local database. Then we look for those runners in the provider to determine if the're just turned off or are gone.

We list the instances in the provider (LXD in this case) and if the instance is not there, we consider that it was removed and clean up both github and our local db.

This seems to have happened at ```2023/06/05 11:26:22```, approximately 4 minutes later. This is unusual for several reasons:

1) if github indicated that a job was completed via a webhook, then that runner should have already been removed from github, thus, the routine that runs every 5 minutes to clean up leftover runners should not have found it.
2) If the runner was marked as ```pending_delete``` it should already have been deleted by the time the cleanup function ran. This indicates that the ```DeleteInstance()``` operation was still stuck somehow trying to delete the runner, which means the provider was either still working on deleting the runner, or the [```op.Wait()```](https://github.com/cloudbase/garm/blob/main/runner/providers/lxd/lxd.go#L379) operation never returned. I will add a timeout on every ```Wait()``` operation. This should return an error back to garm, instances will be properly marked in the database and we should be able to better handle situations such as this.

What was found in the log:

I removed a number of log entries that made it a bit more difficult to parse the log using:

```bash
grep -v 'GET /api/v1/instances HTTP/1.0\|POST /webhooks\|could not find runner details for GitHub Actions\|got hook for org'
```

Found the following:

```txt
2023/06/05 11:22:03 marking instance garm-g1bTYEDUUDJ5 as pending_delete
2023/06/05 11:24:19 marking instance garm-hPQnxqY6Hyqb as pending_delete
2023/06/05 11:25:44 failed to cleanup instance: garm-FeffnyOuuvxZ
2023/06/05 11:25:44 failed to add instance to provider: creating instance: creating instance: waiting for instance to start: websocket: close 1006 (abnormal closure): unexpected EOF
2023/06/05 11:25:44 failed to create instance in provider: creating instance: creating instance: waiting for instance to start: websocket: close 1006 (abnormal closure): unexpected EOF
2023/06/05 11:26:17 failed to add instance to provider: creating instance: creating instance: creating instance: Failed to check for cluster state: context deadline exceeded
2023/06/05 11:26:18 failed to create instance in provider: creating instance: creating instance: creating instance: Failed to check for cluster state: context deadline exceeded
2023/06/05 11:26:20 marking instance garm-ETevs7732xAm as pending_delete
2023/06/05 11:26:22 Runner instance for garm-g1bTYEDUUDJ5 is no longer on the provider, removing from github
2023/06/05 11:26:23 Removing garm-g1bTYEDUUDJ5 from database
```

Which may indicate that your LXD cluster is somewhat overloaded and API calls towards it may fail or take a long time. This could explain the above behavior. This however should be handled in ```garm```.

I will update this issue once I have a PR.

As a curiosity, are you running on an LXD cluster or a single instance? If it's a single server, it may help to cluster it with another one (or add some capacity). I also recommend you try using virtual machines if possible with the LXD provider.

**Comment by gabriel-samfira** [comment]
> @gabriel-samfira btw, thanks for being so active and helping! We're running an average of 11 runners continuously during working hours. 1289 self hosted runners yesterday only! We do have a lot of data and use cases, so feel free to ask if we can help with anything else! hugs bow We're loving garm so far!!

I am thrilled to hear this. So far the issues you opened, are a great help. Most people seem to use garm with a cloud provider like OpenStack or Azure, so there is very little input for situations such as the one described here, where an overloaded provider might trigger some race conditions.

This issue in particular is very valuable as it will help make garm a lot more robust, now that we have a clear issue identified. As much as we try to, we can't think of everything and sometimes we erroneously assume that the systems we depend on can never fail in a certain way. Obviously this was misguided on my part, but fixable :smile:.

**Comment by SystemKeeper** [comment]
Should we remove the ghost container or should it be removed by garm ?

**Comment by gabriel-samfira** [comment]
You may have to remove it yourself if it doesn't show up in ```garm-cli runner ls -a```. Something I'll have to address later.

**Comment by SystemKeeper** [comment]
Okay, just checking 🙂
By the way, in #91 the runners were not listed in `garm-cli runner ls -a` as well

**Comment by gabriel-samfira** [comment]
Hopefully, with the changes here, we will no longer lose track of them.

**Comment by gabriel-samfira** [comment]
fixed by: https://github.com/cloudbase/garm/pull/97
